sudo: false
language: ruby
rvm:
  - 2.4.2
install:
  - bin/setup
script:
  - bundle exec rspec
  - gem build status_check
deploy:
  provider: rubygems
  api_key: "$RUBY_GEMS_API_KEY"
  on:
    branch: master
    tags: true